version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: faceleads-sqlserver
    environment:
      - SA_PASSWORD=Gi@ele0804
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P \"Gi@ele0804\" -Q \"SELECT 1\"" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
